/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.klebermagno.curiosity.model.image;

import com.fasterxml.jackson.annotation.JsonProperty;

public class CameraElement {
	@JsonProperty("full_name")
	private java.lang.String full_name;

 	public void setFull_name(java.lang.String full_name) {
		this.full_name = full_name;
	}

	public java.lang.String getFull_name() {
		return full_name;
	}

	@JsonProperty("name")
	private java.lang.String name;

 	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getName() {
		return name;
	}

}