/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.klebermagno.curiosity.model.image;

import com.fasterxml.jackson.annotation.JsonProperty;

public class PhotoElement {
	@JsonProperty("sol")
	private java.lang.Integer sol;

 	public void setSol(java.lang.Integer sol) {
		this.sol = sol;
	}

	public java.lang.Integer getSol() {
		return sol;
	}

	@JsonProperty("camera")
	private Camera camera;

 	public void setCamera(Camera camera) {
		this.camera = camera;
	}

	public Camera getCamera() {
		return camera;
	}

	@JsonProperty("earth_date")
	private java.lang.String earth_date;

 	public void setEarth_date(java.lang.String earth_date) {
		this.earth_date = earth_date;
	}

	public java.lang.String getEarth_date() {
		return earth_date;
	}

	@JsonProperty("id")
	private java.lang.Integer id;

 	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.Integer getId() {
		return id;
	}

	@JsonProperty("img_src")
	private java.lang.String img_src;

 	public void setImg_src(java.lang.String img_src) {
		this.img_src = img_src;
	}

	public java.lang.String getImg_src() {
		return img_src;
	}

	@JsonProperty("rover")
	private Rover rover;

 	public void setRover(Rover rover) {
		this.rover = rover;
	}

	public Rover getRover() {
		return rover;
	}

}