/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.klebermagno.curiosity.model.image;

import com.fasterxml.jackson.annotation.JsonProperty;

public class Rover {
	@JsonProperty("max_sol")
	private java.lang.Integer max_sol;

 	public void setMax_sol(java.lang.Integer max_sol) {
		this.max_sol = max_sol;
	}

	public java.lang.Integer getMax_sol() {
		return max_sol;
	}

	@JsonProperty("total_photos")
	private java.lang.Integer total_photos;

 	public void setTotal_photos(java.lang.Integer total_photos) {
		this.total_photos = total_photos;
	}

	public java.lang.Integer getTotal_photos() {
		return total_photos;
	}

	@JsonProperty("max_date")
	private java.lang.String max_date;

 	public void setMax_date(java.lang.String max_date) {
		this.max_date = max_date;
	}

	public java.lang.String getMax_date() {
		return max_date;
	}

	@JsonProperty("id")
	private java.lang.Integer id;

 	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.Integer getId() {
		return id;
	}

	@JsonProperty("landing_date")
	private java.lang.String landing_date;

 	public void setLanding_date(java.lang.String landing_date) {
		this.landing_date = landing_date;
	}

	public java.lang.String getLanding_date() {
		return landing_date;
	}

	@JsonProperty("cameras")
	private CameraElement[] cameras;

 	public void setCameras(CameraElement[] cameras) {
		this.cameras = cameras;
	}

	public CameraElement[] getCameras() {
		return cameras;
	}

	@JsonProperty("name")
	private java.lang.String name;

 	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getName() {
		return name;
	}

}