/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.fountainledge.curiosity.model.image;
import com.fasterxml.jackson.annotation.JsonProperty;
public class Camera {
	@JsonProperty("rover_id")
	private java.lang.Integer rover_id;

 	public void setRover_id(java.lang.Integer rover_id) {
		this.rover_id = rover_id;
	}

	public java.lang.Integer getRover_id() {
		return rover_id;
	}

	@JsonProperty("full_name")
	private java.lang.String full_name;

 	public void setFull_name(java.lang.String full_name) {
		this.full_name = full_name;
	}

	public java.lang.String getFull_name() {
		return full_name;
	}

	@JsonProperty("id")
	private java.lang.Integer id;

 	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.Integer getId() {
		return id;
	}

	@JsonProperty("name")
	private java.lang.String name;

 	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getName() {
		return name;
	}

}